proxies:
  - name: "SS-Server"
    type: ss
    server: "43.162.111.97"
    port: 8388
    cipher: chacha20-ietf-poly1305
    password: "sdgf34tgfh"
    udp: true

proxy-groups:
  - name: "PROXY"
    type: select
    proxies:
      - "SS-Server"

rules:
  - DOMAIN-SUFFIX,google.com,PROXY
  - DOMAIN-SUFFIX,youtube.com,PROXY
  - DOMAIN-SUFFIX,github.com,PROXY
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
